import keymirror from 'keymirror';
export default keymirror({
  RequestGetArtists: null,
  FinishGetArtists: null,
  RequestGetPlaylists: null,
  FinishGetPlaylists: null,
  RequestGetPlaylist: null,
  FinishGetPlaylist: null,
  RequestGetFolders: null,
  FinishGetFolders: null,
  RequestGetAlbums: null,
  FinishGetAlbums: null,
  RequestGetSongs: null,
  FinishGetSongs: null,
  SaveConfig: null,
  RequestGetCoverArtURL: null,
  FinishGetCoverArtURL: null,
  Initialize: null,
  SendErrorMessage: null,
  Play: null,
  Pause: null,
  RequestPlay: null,
  RequestPause: null,
  RequestPrev: null,
  RequestNext: null,
  RequestIncreseVolume: null,
  RequestDecreaseVolume: null,
});
