import keymirror from 'keymirror';
export default keymirror({
  RequestGetArtists: null,
  FinishGetArtists: null,
  RequestGetPlaylists: null,
  FinishGetPlaylists: null,
  RequestGetPlaylist: null,
  FinishGetPlaylist: null,
  RequestGetFolders: null,
  FinishGetFolders: null,
  RequestGetAlbums: null,
  FinishGetAlbums: null,
  RequestGetSongs: null,
  FinishGetSongs: null,
  SaveServerConfig: null,
  RequestGetCoverArtURL: null,
  FinishGetCoverArtURL: null,
  Initialize: null,
  SendErrorMessage: null,
});
